apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: hello
build:
  artifacts:
  - image: barolina/hello
    context: hello
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - ingress.yaml
    - pod.yaml
    - service.yaml
