apiVersion: v2
name: hello-chart
description: A Helm chart for Kubernetes (barolina)

type: application

version: 0.4.2
appVersion: 0.1.2

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - myapp-database
