replicaCount: 2

image: barolina/hello

service:
  type: NodePort
  port: 9000
  name: my-app

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  dataDir: /var/lib/postgresql/data/pgdata
  service:
    port: "5432"
    type: NodePort
    nodePort: 32000


persistence:
  mountPath: /var/lib/postgresql	

postgresqlUsername: myuser
postgresqlPassword: passwd
postgresqlDatabase: myapp


metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/larisa"]
