apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "hello-chart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: arch.homework
    http:	
      paths:
        - path: /otusapp/larisa($|/)(.*)
          backend:
            serviceName: {{ include "hello-chart.fullname" . }}
            servicePort: {{ .Values.service.port }}

